### ISSUE TITLE
Describe the different C# classes in detail.

### ISSUE THREAD

**Issue by Rashidovicc** [Rashidovicc/SnakeGame#4]
whrite ...

**Comment by Aliteca** [comment]
Answer:  There are 4 types of classes that we can use in C#:

Static Class: It is the type of class that cannot be instantiated, in other words, we cannot create an object of that class using the new keyword and the class members can be called directly using their class name.
Abstract Class: Abstract classes are declared using the abstract keyword. Objects cannot be created for abstract classes. If you want to use it then it must be inherited in a subclass. You can easily define abstract or non-abstract methods within an Abstract class. The methods inside the abstract class can either have an implementation or no implementation.
Partial Class: It is a type of class that allows dividing their properties, methods, and events into multiple source files, and at compile time these files are combined into a single class.
Sealed Class:  One cannot inherit a sealed class from another class and restricts the class properties. Any access modifiers cannot be applied to the sealed class.
